services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db_ab_data:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      # что-бы можно было подключиться из шторма к бд внутри контейнера
      - "127.0.0.1:53306:3306"

volumes:
  db_ab_data:
